from enum import Enum


class StatType(str, Enum):
    """Spring entity.StatType 대응.

    DB 저장값은 Spring @Enumerated(EnumType.STRING)과 동일하게 enum 멤버 이름
    (예: ATTACK_PERCENT)이다.
    """

    HP = "HP"
    HP_PERCENT = "HP_PERCENT"

    ATTACK = "ATTACK"
    ATTACK_PERCENT = "ATTACK_PERCENT"

    DEFENSE = "DEFENSE"
    DEFENSE_PERCENT = "DEFENSE_PERCENT"

    CRITICAL_RATE = "CRITICAL_RATE"
    CRITICAL_DAMAGE = "CRITICAL_DAMAGE"

    ENERGY_REGEN = "ENERGY_REGEN"

    FUSION_DAMAGE_BONUS = "FUSION_DAMAGE_BONUS"
    GLACIO_DAMAGE_BONUS = "GLACIO_DAMAGE_BONUS"
    AERO_DAMAGE_BONUS = "AERO_DAMAGE_BONUS"
    CONDUCTO_DAMAGE_BONUS = "CONDUCTO_DAMAGE_BONUS"
    SPECTRA_DAMAGE_BONUS = "SPECTRA_DAMAGE_BONUS"
    HAVOC_DAMAGE_BONUS = "HAVOC_DAMAGE_BONUS"

    BASIC_ATTACK_DAMAGE_BONUS = "BASIC_ATTACK_DAMAGE_BONUS"
    HEAVY_ATTACK_DAMAGE_BONUS = "HEAVY_ATTACK_DAMAGE_BONUS"
    RESONANCE_SKILL_DAMAGE_BONUS = "RESONANCE_SKILL_DAMAGE_BONUS"
    RESONANCE_LIBERATION_DAMAGE_BONUS = "RESONANCE_LIBERATION_DAMAGE_BONUS"
    HEALING_BONUS = "HEALING_BONUS"

    ALL_ATTRIBUTE_DAMAGE_BONUS = "ALL_ATTRIBUTE_DAMAGE_BONUS"
    BASIC_AND_HEAVY_ATTACK_DAMAGE_BONUS = "BASIC_AND_HEAVY_ATTACK_DAMAGE_BONUS"
