spring.application.name=wavesync

server.port=8080

spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:postgresql://postgres:5432/wawu
spring.datasource.username=wawu
spring.datasource.password=wawu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



logging.level.root=INFO
logging.level.io.github.wavesync=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%logger{36}] %msg%n


spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB