spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    io.github.wavesync: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%logger{36}] %msg%n"


storage:
  provider: supabase

supabase:
  url: ${SUPABASE_URL}
  service-key: ${SUPABASE_SERVICE_KEY}
  bucket:
    profiles: profile-images
    weapons: weapon-images
    resonator-thumbnails: resonator-thumbnail-images
    resonator-standings: resonator-standing-images


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never