spring:
  application:
    name: wavesync
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true


server:
  port: 8080